// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    // Use a custom fetch to dynamically inject the admin token on every request
    fetch: (url, options) => {
      const token = localStorage.getItem('adminToken');
      const headers = new Headers(options?.headers);
      
      if (token) {
        headers.set('x-admin-token', token);
      }
      
      return fetch(url, { ...options, headers });
    }
  },
});